### PR TITLE
Front profile page

### PR DESCRIPTION
**Pull request by SamanthaLHC**
**what is new :**

- You can change your avatar in the settings (profile button like the intra)
- you can view your stats in "view my profile" (profile button like the intra)

How to check :

- **avatar:**
- [x]  go in settings click on change your avatar.
- [x]  you should be able to upload .gif .jpeg and .png.
➡️ the change is visible immediatly
- [x] now, a pop up appears if you try to upload a bad file like a .pdf or else.

- **view my profile**
- either you play some games or : 
- ➡️ go in prisma add users and edit nbwin and nbloose
- ➡️ in gamehistory, add datas in gagnantid, perdantid, score fields
- [x] check if there is not an inifinite loop (in the f12 console in network tab)
- [ ]  go to "view my profile"You should see the rights datas for ranking and match history leaderboard.
➡️if you want to see the  names in case of changes you need to refresh the page 🤫🫣

### CODE REVIEW

**Review by geekprod27 — CHANGES_REQUESTED** [review]
le nom afficher sur match history sactualise si lautre user change de nom mais pas le rankingimage

le reste me parait ok

**Comment by SamanthaLHC** [comment]
ISSUES FIXED, PR ready to be reviewed again. 🤞

**Review by WickiRiama — COMMENTED** [review]
- [x] Is the @Public decorator necessary in users.controller.ts line 122 ?
- [x] The invalid file pop up doesn't disappear when you upload a new valid image
- [x] In case of equality between 2 users, one is still marked as first and the other as second.
- [x] In case of change of name of one user, if there is an equality, the ladder will change. _For example test1 user and test2 users have 1 victory each. In the ladder, test2 is first and test1 is second. If test2 changes its name, the ladder will change : test1 is first and new_test2 is second._
- [x] There is a bug in the game: the second player does not see the game until the ball starts moving.

**Comment by SamanthaLHC** [comment]
@geekprod27 can you read the comnments? 
- [ ] can you help me for the problem with the equality ? 
- [ ] can you check the public decorator ? 
- [ ] can you see if it is a problem with the lag in the game ? 

Thank you sorry :D

**Comment by geekprod27** [comment]
All fix

**Review by basile41 — APPROVED** [review]
All is good

**Review by basile41 — APPROVED** [review]
All is good

**Review by basile41 — APPROVED** [review]
All is good

**Review by geekprod27 — APPROVED** [review]

**Pull request merged**
