### PR TITLE
Front aff friend

### PR DESCRIPTION
**Pull request by geekprod27**
Add status ( EN LIGNE/ HORS LIGNE/ In GAME )affichage dans la page de profile et sur la liste des amis, en cas de recherche

### CODE REVIEW

**Review by SamanthaLHC — CHANGES_REQUESTED** [review]
- the status is not update in time in the friends bar, so when a player is in game we can't see it (maybe we can fix it with a context or dependencies in useEffect ? )

-  When we enable canardmod the friend button in the user bar, flash like the bread

- There is a massive issue with the game: if we quit it before the end or refresh or close the window all the websites are unusable and it trigger an error: 
the Db seems to be broken and only a make re let us to retry.

``` Uncaught runtime errors:
ERROR
NetworkError when attempting to fetch resource. ``

**Comment by WickiRiama** [comment]
When a user close the navigator during a game, the two players keep indefinitely the status in game.

**Comment by geekprod27** [comment]
c'est fix

**Comment by WickiRiama** [comment]
It seems to work OK !

**Pull request merged**
